"""The checked-in stubs and the docs must describe the built package.

The stubs (python/silt/*.pyi) are regenerated by every build (see
python/CMakeLists.txt); these tests fail when they are missing or stale.
"""

import ast
import importlib.util
import pathlib
import re

import pytest

import silt

ROOT = pathlib.Path(__file__).resolve().parent.parent
STUB_DIR = ROOT / "python" / "silt"
PACKAGE_STUB = STUB_DIR / "__init__.pyi"
EXTENSION_STUB = STUB_DIR / "silt.pyi"


def _stub_names(path):
    """Top-level names a stub defines (classes, functions, annotated values)."""
    names = set()
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, (ast.ClassDef, ast.FunctionDef)):
            names.add(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
    return names


def _load_pyapi():
    spec = importlib.util.spec_from_file_location("pyapi", ROOT / "doc" / "pyapi.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def stubs():
    for path in (PACKAGE_STUB, EXTENSION_STUB):
        assert path.exists(), f"{path} is missing -- rebuild to generate the stubs, and commit them"
    return _stub_names(PACKAGE_STUB) | _stub_names(EXTENSION_STUB)


def _public(names):
    return sorted(n for n in names if not n.startswith("_"))


def test_every_public_name_is_stubbed(stubs):
    missing = [n for n in _public(silt.__all__) if n not in stubs]
    assert not missing, f"names missing from python/silt/*.pyi (stale stubs?): {missing}"


def test_stub_all_matches_the_module():
    stub_all = _public(_load_pyapi().public_names(PACKAGE_STUB))
    assert stub_all == _public(silt.__all__), "python/silt/__init__.pyi __all__ differs from silt.__all__"


def test_in_place_operations_are_stubbed(stubs):
    # stubgen drops trailing-underscore names unless told otherwise.
    in_place = [n for n in _public(dir(silt)) if n.endswith("_")]
    assert in_place
    assert all(n in stubs for n in in_place)


def test_python_reference_documents_every_public_name(stubs):
    text = _load_pyapi().render(PACKAGE_STUB, EXTENSION_STUB)
    documented = set(re.findall(r"^\.\. py:(?:class|function|data):: (\w+)", text, flags=re.M))
    missing = [n for n in _public(silt.__all__) if n not in documented]
    assert not missing, f"public names missing from the rendered Python reference: {missing}"


def test_cpp_reference_lists_every_header():
    listed = set(re.findall(r"doxygenfile:: (\S+)", (ROOT / "doc" / "api_cpp.rst").read_text(encoding="utf-8")))
    headers = {p.name for p in (ROOT / "source" / "silt").rglob("*.hpp")} - {"silt.hpp"}
    assert headers <= listed, f"headers missing from doc/api_cpp.rst: {sorted(headers - listed)}"
