"""silt python bindings"""

from collections.abc import Iterator, List, Sequence
import enum
from typing import overload


class shape:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> None: ...

    @property
    def dim(self) -> int: ...

    @property
    def elem(self) -> int: ...

    @property
    def ext(self) -> List[int]: ...

    def __getitem__(self, arg: int, /) -> int: ...

    def reshape(self, d0: int = 1, d1: int = 1, d2: int = 1, d3: int = 1) -> shape: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: object, /) -> bool: ...

class slice:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, /) -> None: ...

    @overload
    def __init__(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> None: ...

    @property
    def dim(self) -> int: ...

    @property
    def shape(self) -> shape: ...

    @property
    def maxelem(self) -> int: ...

    @property
    def elem(self) -> int: ...

    @property
    def offset(self) -> List[int]: ...

    @property
    def stride(self) -> List[int]: ...

    @property
    def extent(self) -> List[int]: ...

    def reset(self) -> None: ...

    def index(self, arg0: int, arg1: int, arg2: int, arg3: int, /) -> None: ...

    def transform(self, arg: int, /) -> int: ...

    def __repr__(self) -> str: ...

class tensor:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, arg0: dtype, arg1: shape, /) -> None: ...

    @overload
    def __init__(self, arg0: dtype, arg1: shape, arg2: host, /) -> None: ...

    @property
    def type(self) -> dtype: ...

    @property
    def elem(self) -> int: ...

    @property
    def size(self) -> int: ...

    @property
    def nbytes(self) -> int: ...

    @property
    def host(self) -> host: ...

    @property
    def shape(self) -> shape: ...

    @property
    def dtype(self) -> dtype: ...

    @property
    def ndim(self) -> int: ...

    def __repr__(self) -> str: ...

    def __len__(self) -> int: ...

    def __iter__(self) -> Iterator: ...

    def item(self) -> object: ...

    def to(self, arg: host, /) -> tensor: ...

    def to_cpu(self) -> tensor: ...

    def to_gpu(self) -> tensor: ...

    def copy_to(self, host: host | None = None) -> tensor: ...

    def reshape(self, d0: int = 1, d1: int = 1, d2: int = 1, d3: int = 1) -> tensor: ...

    def flatten(self) -> tensor: ...

    def __getitem__(self, arg: tuple, /) -> view: ...

    def slice(self, arg: tuple, /) -> view: ...

    def numpy(self) -> object: ...

    def __array__(self, dtype: object | None = None, copy: object | None = None) -> object: ...

    @staticmethod
    def from_numpy(arg: object, /) -> tensor: ...

    def torch(self) -> object: ...

    @staticmethod
    def from_torch(arg: object, /) -> tensor: ...

class view:
    @property
    def type(self) -> dtype: ...

    @property
    def elem(self) -> int: ...

    @property
    def host(self) -> host: ...

    @property
    def slice(self) -> slice: ...

    @property
    def dtype(self) -> dtype: ...

    def __repr__(self) -> str: ...

@overload
def set_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def set_(arg0: view, arg1: view, /) -> None: ...

@overload
def set_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def set_(arg0: view, arg1: object, /) -> None: ...

@overload
def add_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def add_(arg0: view, arg1: view, /) -> None: ...

@overload
def add_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def add_(arg0: view, arg1: object, /) -> None: ...

@overload
def multiply_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def multiply_(arg0: view, arg1: view, /) -> None: ...

@overload
def multiply_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def multiply_(arg0: view, arg1: object, /) -> None: ...

@overload
def divide_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def divide_(arg0: view, arg1: view, /) -> None: ...

@overload
def divide_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def divide_(arg0: view, arg1: object, /) -> None: ...

@overload
def mix_(arg0: tensor, arg1: tensor, arg2: float, /) -> None: ...

@overload
def mix_(arg0: view, arg1: view, arg2: float, /) -> None: ...

@overload
def clamp_(arg0: tensor, arg1: float, arg2: float, /) -> None: ...

@overload
def clamp_(arg0: view, arg1: float, arg2: float, /) -> None: ...

@overload
def minimum_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def minimum_(arg0: view, arg1: view, /) -> None: ...

@overload
def minimum_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def minimum_(arg0: view, arg1: object, /) -> None: ...

@overload
def maximum_(arg0: tensor, arg1: tensor, /) -> None: ...

@overload
def maximum_(arg0: view, arg1: view, /) -> None: ...

@overload
def maximum_(arg0: tensor, arg1: object, /) -> None: ...

@overload
def maximum_(arg0: view, arg1: object, /) -> None: ...

def cast(arg0: tensor, arg1: dtype, /) -> object: ...

def sum(arg: tensor, /) -> object: ...

def mean(arg: tensor, /) -> object: ...

def min(arg: tensor, /) -> object: ...

def max(arg: tensor, /) -> object: ...

def var(arg: tensor, /) -> object: ...

def std(arg: tensor, /) -> object: ...

def argmin(arg: tensor, /) -> object: ...

def argmax(arg: tensor, /) -> object: ...

def sort_(arg: tensor, /) -> None: ...

def argsort(arg: tensor, /) -> tensor: ...

@overload
def histogram(arg0: tensor, arg1: int, arg2: object, arg3: object, /) -> tensor: ...

@overload
def histogram(arg0: view, arg1: int, arg2: object, arg3: object, /) -> tensor: ...

def synchronize() -> None: ...

def index_radius(arg0: shape, arg1: Sequence[float], arg2: float, /) -> tensor: ...

def index_box(arg0: shape, arg1: Sequence[float], arg2: Sequence[float], /) -> tensor: ...

def index_polygon(arg0: shape, arg1: Sequence[Sequence[float]], /) -> tensor: ...

def index_range(arg0: tensor, arg1: object, arg2: object, /) -> tensor: ...

def index_greater(arg0: tensor, arg1: object, /) -> tensor: ...

def index_lesser(arg0: tensor, arg1: object, /) -> tensor: ...

def index_match(arg0: tensor, arg1: object, /) -> tensor: ...

def index_slice(arg: slice, /) -> tensor: ...

def index_sort_unique(arg: tensor, /) -> tensor: ...

def index_union(arg0: tensor, arg1: tensor, /) -> tensor: ...

def index_intersection(arg0: tensor, arg1: tensor, /) -> tensor: ...

def index_difference(arg0: tensor, arg1: tensor, /) -> tensor: ...

def index_symmetric_difference(arg0: tensor, arg1: tensor, /) -> tensor: ...

def index_complement(arg0: tensor, arg1: shape, /) -> tensor: ...

@overload
def indexed_set(arg0: tensor, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_set(arg0: view, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_add_(arg0: tensor, arg1: tensor, arg2: tensor, /) -> None: ...

@overload
def indexed_add_(arg0: tensor, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_add_(arg0: view, arg1: view, arg2: tensor, /) -> None: ...

@overload
def indexed_add_(arg0: view, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_multiply_(arg0: tensor, arg1: tensor, arg2: tensor, /) -> None: ...

@overload
def indexed_multiply_(arg0: tensor, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_multiply_(arg0: view, arg1: view, arg2: tensor, /) -> None: ...

@overload
def indexed_multiply_(arg0: view, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_divide_(arg0: tensor, arg1: tensor, arg2: tensor, /) -> None: ...

@overload
def indexed_divide_(arg0: tensor, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_divide_(arg0: view, arg1: view, arg2: tensor, /) -> None: ...

@overload
def indexed_divide_(arg0: view, arg1: object, arg2: tensor, /) -> None: ...

@overload
def indexed_mix_(arg0: tensor, arg1: tensor, arg2: tensor, arg3: float, /) -> None: ...

@overload
def indexed_mix_(arg0: view, arg1: view, arg2: tensor, arg3: float, /) -> None: ...

@overload
def gather(arg0: tensor, arg1: tensor, /) -> tensor: ...

@overload
def gather(arg0: view, arg1: tensor, /) -> tensor: ...

@overload
def scatter_(arg0: tensor, arg1: tensor, arg2: tensor, /) -> None: ...

@overload
def scatter_(arg0: view, arg1: tensor, arg2: tensor, /) -> None: ...

@overload
def indexed_sum(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_sum(arg0: view, arg1: tensor, /) -> object: ...

@overload
def indexed_mean(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_mean(arg0: view, arg1: tensor, /) -> object: ...

@overload
def indexed_min(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_min(arg0: view, arg1: tensor, /) -> object: ...

@overload
def indexed_max(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_max(arg0: view, arg1: tensor, /) -> object: ...

@overload
def indexed_argmin(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_argmin(arg0: view, arg1: tensor, /) -> object: ...

@overload
def indexed_argmax(arg0: tensor, arg1: tensor, /) -> object: ...

@overload
def indexed_argmax(arg0: view, arg1: tensor, /) -> object: ...

def seed(arg0: tensor, arg1: int, arg2: int, /) -> None: ...

@overload
def sample_uniform(arg: tensor, /) -> tensor: ...

@overload
def sample_uniform(arg0: tensor, arg1: float, arg2: float, /) -> tensor: ...

@overload
def sample_normal(arg: tensor, /) -> tensor: ...

@overload
def sample_normal(arg0: tensor, arg1: float, arg2: float, /) -> tensor: ...

class dtype(enum.Enum):
    int = 1

    float32 = 2

    float64 = 3

    rng = 4

    int64 = 5

int: dtype = dtype.int

float32: dtype = dtype.float32

float64: dtype = dtype.float64

rng: dtype = dtype.rng

int64: dtype = dtype.int64

class host(enum.Enum):
    cpu = 0

    gpu = 1

cpu: host = host.cpu

gpu: host = host.gpu
